import type { Metadata } from "next";
import Auth from "@/components/Auth";
import { ThemeProvider } from "@/components/theme-provider";
import "../../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <Auth>{children}</Auth>
      </ThemeProvider>
    </main>
  );
}
