import type { Metadata } from "next";
import "../globals.css";
import Layout from "@/modules/dashboard/layout";
import Auth from "@/components/Auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <Auth>
        <Layout>{children}</Layout>
      </Auth>
    </main>
  );
}
